#!/usr/bin/env node

'use strict'

const execSync = require('child_process').execSync
const direction = process.argv[2] // [up/down]
const orm = process.argv[3] // [sequelize|knex]
const database = process.argv[5] ? process.argv[4] : 'pg' // pg | mysql2
const connection = process.argv[5] ? process.argv[5] : process.argv[4] // [postgres://user:password@host/database_name]
let ormPackage = orm == 'sequelize' ? 'sequelize-cli' : orm

const runCommand = command => {
  console.log(`running command:`, command)
  execSync(command, {stdio: 'inherit'})
}

runCommand(`npm install ${database}`)

if (orm === 'sequelize') {
  runCommand(`npm install ${orm}`)
  runCommand(`npm install ${ormPackage}`)
  const method = direction === 'down' ? ':undo' : ''
  runCommand(`node_modules/.bin/sequelize db:migrate${method} --url ${connection}`)
} else if (orm === 'knex') {
  runCommand(`npm install ${orm}`)
  const method = direction === 'down' ? ':rollback' : ':latest'
  runCommand(`node_modules/.bin/knex migrate${method} --client=pg --connection='${connection}' --migrations-directory=./migrations`)
}
